export const fieldCheckTheme = {
  colors: {
    navy: '#123c69',
    navyDark: '#071d36',
    green: '#087f3a',
    greenSoft: '#e7f7ee',
    blue: '#1f7ae0',
    blueSoft: '#eaf3ff',
    amber: '#f59e0b',
    amberSoft: '#fff7e6',
    red: '#b42318',
    redSoft: '#fff1f0',
    purple: '#7c3aed',
    purpleSoft: '#f3eafd',
    background: '#f4f7fb',
    card: '#ffffff',
    text: '#111827',
    muted: '#667085',
    border: '#dce2e9',
    surfaceAlt: '#f8fafc',
    offline: '#b45309',
    black: '#020617',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 22,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
  },
  typography: {
    title: 24,
    subtitle: 15,
    body: 14,
    small: 12,
  },
  shadows: {
    card: {
      shadowColor: '#102f52',
      shadowOpacity: 0.08,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 8 },
      elevation: 2,
    },
  },
  statusColors: {
    pendente: { color: '#b45309', backgroundColor: '#fff7e6' },
    em_andamento: { color: '#1f7ae0', backgroundColor: '#eaf3ff' },
    andamento: { color: '#1f7ae0', backgroundColor: '#eaf3ff' },
    concluido: { color: '#087f3a', backgroundColor: '#e7f7ee' },
    finalizado: { color: '#087f3a', backgroundColor: '#e7f7ee' },
    aprovado: { color: '#087f3a', backgroundColor: '#e7f7ee' },
    sincronizando: { color: '#7c3aed', backgroundColor: '#f3eafd' },
    sincronizado: { color: '#087f3a', backgroundColor: '#e7f7ee' },
    erro: { color: '#b42318', backgroundColor: '#fff1f0' },
    critico: { color: '#b42318', backgroundColor: '#fff1f0' },
    offline: { color: '#b45309', backgroundColor: '#fff7e6' },
    local: { color: '#334155', backgroundColor: '#eef2f7' },
  },
  moduleColors: {
    entrega: { color: '#087f3a', backgroundColor: '#e7f7ee' },
    preventiva: { color: '#1f7ae0', backgroundColor: '#eaf3ff' },
    corretiva: { color: '#b45309', backgroundColor: '#fff7e6' },
    auditoria: { color: '#7c3aed', backgroundColor: '#f3eafd' },
    seguranca: { color: '#b42318', backgroundColor: '#fff1f0' },
    inventario: { color: '#0f766e', backgroundColor: '#e6fffb' },
    repositor: { color: '#334155', backgroundColor: '#eef2f7' },
    ia: { color: '#7c3aed', backgroundColor: '#f3eafd' },
  },
  darkMode: {
    prepared: true,
    background: '#020617',
    card: '#0f172a',
    text: '#f8fafc',
  },
};
